name: Push image to docker hub registry


on:
  push:
    branches:
      - master

jobs:
  push:
    name: Push image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set-up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}" 
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            msa3dfa/bun-dockerized:latest
            msa3dfa/bun-dockerized:${{ github.sha }}
