name: Run test in docker compose

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run test in docker compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose run test
